[platformio]
default_envs = wohnzimmer

[env]
platform  = espressif32 @ ^6.5.0
framework = arduino
monitor_speed = 115200
upload_speed  = 921600

lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0
    madhephaestus/ESP32Encoder @ ^0.11.1

build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

[env:wohnzimmer]
board = esp32-s3-devkitc-1
board_build.mcu        = esp32s3
board_build.f_cpu      = 240000000L
board_build.partitions = partitions_large.csv
upload_port  = /dev/cu.usbmodem31201
monitor_port = /dev/cu.usbmodem31201

build_flags =
    ${env.build_flags}
    -DCADEN_ROOM_ID='"wohnzimmer"'
    -DCADEN_HAS_DISPLAY=1
    -DI2S_MCLK=2
    -DI2S_BCLK=48
    -DI2S_WS=38
    -DI2S_DIN=39
    -DI2S_DOUT=47
    -DI2C_SDA=11
    -DI2C_SCL=10
    -DCODEC_PA_PIN=15

[env:schlafzimmer]
board = esp32-s3-devkitc-1
board_build.mcu        = esp32s3
board_build.f_cpu      = 240000000L
board_build.partitions = partitions_large.csv

build_flags =
    ${env.build_flags}
    -DCADEN_ROOM_ID='"schlafzimmer"'
    -DCADEN_HAS_DISPLAY=0
    -DI2S_MCLK=12
    -DI2S_BCLK=13
    -DI2S_WS=14
    -DI2S_DIN=15
    -DI2S_DOUT=16
    -DI2C_SDA=11
    -DI2C_SCL=10
    -DCODEC_PA_PIN=-1
